### ISSUE TITLE
Is this package working

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [BosNaufal/vue-image-compressor#4]

**Comment by crushman1** [comment]
i dont think so. I have tried it and spent some hours trying to get it working. no matter what file i compress, it shows the size of 6 bites and the result picture doesnt open. it says the file type is jpeg but its something else. Firebase storage says its type : `application/octet-stream`

**Comment by backswordit2020** [comment]
open src/components/vue-image-compressor.vue   
find function drawImage,add img.onload at line 106
find function buildFile, return new File([blob], name)   =>  return new File([blob], name, { type: 'image/jpeg' }) 
![微信截图_20201117144346](https://user-images.githubusercontent.com/74586102/99355526-6c06bc00-28e3-11eb-8c39-4898b02581f5.png)
![微信截图_20201117161250](https://user-images.githubusercontent.com/74586102/99363509-cc9bf600-28ef-11eb-8d5c-20f30817cc75.png)
